apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-webapp
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      containers:
      - name: simple-webapp
        image: projectacr-h9f7f2cyakbkdcft.azurecr.io/simple-webapp:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 8080
